'''
Interrupting Normal exception of a code is called Exception or Error
we will handle by using Error handling

syntax:

try:
  risky code
exception:
  print("error")
else:
  print("No error")
finally
  print("always")  
    
'''

try:
     print(b) # ricky code
except:
    print("error")
else:
    print("No error")
finally:
    print("always")                 
     